export const themes = {
  tecnologia: {
    primary: 'bg-blue-600',
    text: 'text-blue-600',
    border: 'border-blue-200',
    bgLight: 'bg-blue-50',
    icon: 'Code2',
    hex: '#3b82f6',
    hexSecondary: '#60a5fa',
    hexDark: '#1d4ed8',
    emoji: '💻',
  },
  saude: {
    primary: 'bg-emerald-500',
    text: 'text-emerald-600',
    border: 'border-emerald-200',
    bgLight: 'bg-emerald-50',
    icon: 'Heart',
    hex: '#10b981',
    hexSecondary: '#34d399',
    hexDark: '#047857',
    emoji: '❤️',
  },
  gastronomia: {
    primary: 'bg-orange-500',
    text: 'text-orange-600',
    border: 'border-orange-200',
    bgLight: 'bg-orange-50',
    icon: 'ChefHat',
    hex: '#f97316',
    hexSecondary: '#fbbf24',
    hexDark: '#c2410c',
    emoji: '🍳',
  },
  vendas: {
    primary: 'bg-purple-500',
    text: 'text-purple-600',
    border: 'border-purple-200',
    bgLight: 'bg-purple-50',
    icon: 'ShoppingBag',
    hex: '#8b5cf6',
    hexSecondary: '#a78bfa',
    hexDark: '#6d28d9',
    emoji: '🛒',
  },
  administrativo: {
    primary: 'bg-teal-500',
    text: 'text-teal-600',
    border: 'border-teal-200',
    bgLight: 'bg-teal-50',
    icon: 'ClipboardList',
    hex: '#14b8a6',
    hexSecondary: '#5eead4',
    hexDark: '#0f766e',
    emoji: '📋',
  },
  logistica: {
    primary: 'bg-sky-600',
    text: 'text-sky-700',
    border: 'border-sky-200',
    bgLight: 'bg-sky-50',
    icon: 'Package',
    hex: '#0284c7',
    hexSecondary: '#38bdf8',
    hexDark: '#0c4a6e',
    emoji: '📦',
  },
  educacao: {
    primary: 'bg-indigo-500',
    text: 'text-indigo-600',
    border: 'border-indigo-200',
    bgLight: 'bg-indigo-50',
    icon: 'GraduationCap',
    hex: '#6366f1',
    hexSecondary: '#818cf8',
    hexDark: '#3730a3',
    emoji: '📚',
  },
  marketing: {
    primary: 'bg-pink-500',
    text: 'text-pink-600',
    border: 'border-pink-200',
    bgLight: 'bg-pink-50',
    icon: 'Megaphone',
    hex: '#ec4899',
    hexSecondary: '#f9a8d4',
    hexDark: '#9d174d',
    emoji: '📢',
  },
  design: {
    primary: 'bg-violet-500',
    text: 'text-violet-600',
    border: 'border-violet-200',
    bgLight: 'bg-violet-50',
    icon: 'Palette',
    hex: '#7c3aed',
    hexSecondary: '#c4b5fd',
    hexDark: '#4c1d95',
    emoji: '🎨',
  },
  engenharia: {
    primary: 'bg-slate-600',
    text: 'text-slate-700',
    border: 'border-slate-200',
    bgLight: 'bg-slate-50',
    icon: 'Ruler',
    hex: '#475569',
    hexSecondary: '#94a3b8',
    hexDark: '#1e293b',
    emoji: '⚙️',
  },
  construcao: {
    primary: 'bg-amber-600',
    text: 'text-amber-700',
    border: 'border-amber-200',
    bgLight: 'bg-amber-50',
    icon: 'HardHat',
    hex: '#d97706',
    hexSecondary: '#fcd34d',
    hexDark: '#92400e',
    emoji: '🏗️',
  },
  beleza: {
    primary: 'bg-pink-400',
    text: 'text-pink-500',
    border: 'border-pink-100',
    bgLight: 'bg-pink-50',
    icon: 'Sparkles',
    hex: '#f472b6',
    hexSecondary: '#fbcfe8',
    hexDark: '#be185d',
    emoji: '💅',
  },
  seguranca: {
    primary: 'bg-slate-800',
    text: 'text-slate-900',
    border: 'border-slate-300',
    bgLight: 'bg-slate-100',
    icon: 'Shield',
    hex: '#1e293b',
    hexSecondary: '#475569',
    hexDark: '#0f172a',
    emoji: '🛡️',
  },
  limpeza: {
    primary: 'bg-cyan-500',
    text: 'text-cyan-600',
    border: 'border-cyan-200',
    bgLight: 'bg-cyan-50',
    icon: 'Wind',
    hex: '#06b6d4',
    hexSecondary: '#67e8f9',
    hexDark: '#0e7490',
    emoji: '✨',
  },
  agro: {
    primary: 'bg-lime-600',
    text: 'text-lime-700',
    border: 'border-lime-200',
    bgLight: 'bg-lime-50',
    icon: 'Sprout',
    hex: '#65a30d',
    hexSecondary: '#a3e635',
    hexDark: '#365314',
    emoji: '🌱',
  },
  juridico: {
    primary: 'bg-blue-900',
    text: 'text-blue-900',
    border: 'border-blue-200',
    bgLight: 'bg-blue-50',
    icon: 'Scale',
    hex: '#1e3a8a',
    hexSecondary: '#3b82f6',
    hexDark: '#172554',
    emoji: '⚖️',
  },
  turismo: {
    primary: 'bg-orange-600',
    text: 'text-orange-700',
    border: 'border-orange-200',
    bgLight: 'bg-orange-50',
    icon: 'Plane',
    hex: '#ea580c',
    hexSecondary: '#fdba74',
    hexDark: '#7c2d12',
    emoji: '✈️',
  },
  industria: {
    primary: 'bg-red-700',
    text: 'text-red-800',
    border: 'border-red-200',
    bgLight: 'bg-red-50',
    icon: 'Factory',
    hex: '#b91c1c',
    hexSecondary: '#f87171',
    hexDark: '#7f1d1d',
    emoji: '🏭',
  },
  default: {
    primary: 'bg-slate-800',
    text: 'text-slate-800',
    border: 'border-slate-200',
    bgLight: 'bg-slate-50',
    icon: 'Briefcase',
    hex: '#334155',
    hexSecondary: '#64748b',
    hexDark: '#1e293b',
    emoji: '💼',
  }
};

export type ThemeKey = keyof typeof themes;

export const getTheme = (slug: string) => {
  return themes[slug as ThemeKey] || themes.default;
};
