import type { SectionDefinition, SectionKey } from '@/types/site';

export const sections: SectionDefinition[] = [
  {
    key: 'hero',
    label: 'Resumo Profissional',
    labelPlural: 'Resumo Profissional',
    source: 'profile',
    editable: true,
    hasSummary: false,
    hasSettings: true,
    icon: 'User',
    color: 'blue',
  },
  {
    key: 'experiences',
    label: 'Experiências',
    labelPlural: 'Experiências',
    source: 'profile',
    editable: false,
    hasSummary: false,
    hasSettings: false,
    icon: 'Briefcase',
    color: 'indigo',
  },
  {
    key: 'services_intro',
    label: 'Resumo dos Serviços',
    labelPlural: 'Resumo dos Serviços',
    source: 'custom',
    editable: true,
    hasSummary: true,
    hasSettings: false,
    icon: 'FileText',
    color: 'green',
  },
  {
    key: 'services',
    label: 'Serviços',
    labelPlural: 'Serviços',
    source: 'services',
    editable: true,
    hasSummary: false,
    hasSettings: false,
    icon: 'Package',
    color: 'emerald',
  },
  {
    key: 'projects',
    label: 'Projetos',
    labelPlural: 'Projetos',
    source: 'profile',
    editable: false,
    hasSummary: false,
    hasSettings: false,
    icon: 'FolderKanban',
    color: 'purple',
  },
  {
    key: 'trajectory',
    label: 'Trajetória',
    labelPlural: 'Trajetória',
    source: 'custom',
    editable: true,
    hasSummary: true,
    hasSettings: false,
    icon: 'Route',
    color: 'orange',
  },
  {
    key: 'education',
    label: 'Educação',
    labelPlural: 'Formação',
    source: 'profile',
    editable: false,
    hasSummary: false,
    hasSettings: false,
    icon: 'GraduationCap',
    color: 'teal',
  },
  {
    key: 'skills',
    label: 'Habilidades',
    labelPlural: 'Habilidades',
    source: 'profile',
    editable: false,
    hasSummary: false,
    hasSettings: false,
    icon: 'Zap',
    color: 'yellow',
  },
  {
    key: 'certifications',
    label: 'Certificações',
    labelPlural: 'Certificações',
    source: 'profile',
    editable: false,
    hasSummary: false,
    hasSettings: false,
    icon: 'Award',
    color: 'amber',
  },
  {
    key: 'languages',
    label: 'Idiomas',
    labelPlural: 'Idiomas',
    source: 'profile',
    editable: false,
    hasSummary: false,
    hasSettings: false,
    icon: 'Languages',
    color: 'cyan',
  },
  {
    key: 'blog',
    label: 'Blog',
    labelPlural: 'Blog',
    source: 'posts',
    editable: true,
    hasSummary: false,
    hasSettings: false,
    icon: 'BookOpen',
    color: 'rose',
  },
  {
    key: 'links',
    label: 'Links',
    labelPlural: 'Links',
    source: 'external',
    editable: true,
    hasSummary: false,
    hasSettings: false,
    icon: 'Link',
    color: 'slate',
  },
  {
    key: 'recommendations',
    label: 'Depoimentos',
    labelPlural: 'Depoimentos',
    source: 'profile',
    editable: false,
    hasSummary: false,
    hasSettings: false,
    icon: 'MessageSquare',
    color: 'pink',
  },
  {
    key: 'volunteer',
    label: 'Voluntariado',
    labelPlural: 'Voluntariado',
    source: 'profile',
    editable: false,
    hasSummary: false,
    hasSettings: false,
    icon: 'Heart',
    color: 'red',
  },
  {
    key: 'publications',
    label: 'Publicações',
    labelPlural: 'Publicações',
    source: 'profile',
    editable: false,
    hasSummary: false,
    hasSettings: false,
    icon: 'Newspaper',
    color: 'violet',
  },
];

export function getSectionDefinition(key: SectionKey): SectionDefinition | undefined {
  return sections.find((s) => s.key === key);
}

export function getSectionColor(key: SectionKey): string {
  const def = getSectionDefinition(key);
  return def?.color || 'gray';
}
