-- Inserção em massa de 255 habilidades na tabela `skills`
-- O ícone padrão 'Star' será usado conforme definido no esquema da tabela.

INSERT INTO skills (name) VALUES
('Comunicação Efetiva'),
('Trabalho em Equipe'),
('Resolução de Problemas'),
('Pensamento Crítico'),
('Criatividade'),
('Liderança'),
('Adaptabilidade'),
('Gerenciamento de Tempo'),
('Inteligência Emocional'),
('Negociação'),
('Persuasão'),
('Resiliência'),
('Empatia'),
('Escuta Ativa'),
('Feedback Construtivo'),
('Mentoria'),
('Oratória'),
('Facilitação de Reuniões'),
('Resolução de Conflitos'),
('Tomada de Decisão'),
('Proatividade'),
('Vontade de Aprender'),
('Facilidade com Tecnologia'),
('Organização'),
('Planejamento Estratégico'),
('Gestão de Projetos'),
('Metodologias Ágeis'),
('Scrum'),
('Kanban'),
('Gestão de Produtos'),
('Análise de Negócios'),
('Análise de Dados'),
('Gestão de Pessoas'),
('Orçamento'),
('OKR (Objectives and Key Results)'),
('JavaScript'),
('TypeScript'),
('Python'),
('Java'),
('C#'),
('C++'),
('Go (Golang)'),
('Rust'),
('PHP'),
('Ruby'),
('Swift'),
('Kotlin'),
('SQL'),
('NoSQL'),
('MongoDB'),
('PostgreSQL'),
('MySQL'),
('SQLite'),
('Firebase'),
('Supabase'),
('Docker'),
('Kubernetes'),
('Git'),
('CI/CD (Integração Contínua/Entrega Contínua)'),
('Jenkins'),
('GitLab CI'),
('GitHub Actions'),
('React'),
('Angular'),
('Vue.js'),
('Svelte'),
('Node.js'),
('Express.js'),
('Nest.js'),
('Django'),
('Flask'),
('Spring Boot'),
('.NET Core'),
('TDD (Test-Driven Development)'),
('BDD (Behavior-Driven Development)'),
('Testes Unitários'),
('Testes de Integração'),
('Testes End-to-End (E2E)'),
('Arquitetura de Microsserviços'),
('REST APIs'),
('GraphQL'),
('gRPC'),
('AWS (Amazon Web Services)'),
('Microsoft Azure'),
('Google Cloud Platform (GCP)'),
('Linux'),
('Bash Scripting'),
('HTML5'),
('CSS3'),
('Sass/SCSS'),
('LESS'),
('Tailwind CSS'),
('Bootstrap'),
('UI (User Interface) Design'),
('UX (User Experience) Design'),
('Design Thinking'),
('Figma'),
('Adobe XD'),
('Sketch'),
('Prototipagem'),
('Pesquisa de Usuário'),
('Jornada do Usuário'),
('Arquitetura da Informação'),
('Design System'),
('Adobe Photoshop'),
('Adobe Illustrator'),
('Design de Interação'),
('Power BI'),
('Tableau'),
('Excel Avançado'),
('Google Analytics'),
('Marketing Digital'),
('SEO (Search Engine Optimization)'),
('SEM (Search Engine Marketing)'),
('Marketing de Conteúdo'),
('Copywriting'),
('Redes Sociais'),
('Email Marketing'),
('Automação de Marketing'),
('Escrita Técnica'),
('Inglês Fluente'),
('Espanhol Avançado'),
('Comunicação Interpessoal'),
('Pensamento Analítico'),
('Gerenciamento de Stakeholders'),
('Liderança de Equipe'),
('Desenvolvimento de Carreira'),
('Inteligência de Mercado'),
('Análise Competitiva'),
('Modelagem de Dados'),
('Data Warehousing'),
('ETL (Extract, Transform, Load)'),
('Machine Learning'),
('Inteligência Artificial'),
('Visão Computacional'),
('Processamento de Linguagem Natural (PLN)'),
('TensorFlow'),
('PyTorch'),
('Scikit-learn'),
('Pandas'),
('NumPy'),
('DevOps'),
('Infraestrutura como Código (IaC)'),
('Terraform'),
('Ansible'),
('Monitoramento de Sistemas'),
('Prometheus'),
('Grafana'),
('Segurança da Informação'),
('Pentest (Teste de Invasão)'),
('Análise de Vulnerabilidades'),
('Criptografia'),
('Redes de Computadores'),
('Web Scraping'),
('Automação de Processos (RPA)'),
('Desenvolvimento Mobile'),
('React Native'),
('Flutter'),
('Desenvolvimento iOS Nativo'),
('Desenvolvimento Android Nativo'),
('WordPress'),
('Shopify'),
('Magento'),
('Webflow'),
('Fotografia'),
('Edição de Vídeo'),
('Adobe Premiere Pro'),
('Final Cut Pro'),
('Blender'),
('Autodesk Maya'),
('Game Design'),
('Game Development'),
('Unity Engine'),
('Unreal Engine'),
('Contabilidade'),
('Finanças Corporativas'),
('Análise Financeira'),
('Recrutamento e Seleção'),
('Treinamento e Desenvolvimento'),
('Direito Empresarial'),
('Propriedade Intelectual'),
('Sucesso do Cliente (Customer Success)'),
('Suporte Técnico'),
('Vendas B2B'),
('Vendas B2C'),
('Gestão de Contas'),
('Inbound Marketing'),
('Outbound Marketing'),
('Growth Hacking'),
('Product-Led Growth (PLG)'),
('E-commerce'),
('Logística'),
('Gestão da Cadeia de Suprimentos'),
('Jornalismo de Dados'),
('Visualização de Dados'),
('D3.js'),
('Storytelling com Dados'),
('Blockchain'),
('Desenvolvimento de Smart Contracts'),
('Solidarity'),
('Web3'),
('Realidade Aumentada (AR)'),
('Realidade Virtual (VR)'),
('Impressão 3D'),
('IoT (Internet das Coisas)'),
('Hardware Hacking'),
('Design Instrucional'),
('Educação Online'),
('Consultoria de Gestão'),
('Consultoria de TI'),
('Auditoria'),
('Relações Públicas'),
('Comunicação Corporativa'),
('Branding (Gestão de Marca)'),
('Pesquisa de Mercado'),
('Análise de Sentimento'),
('Design de Som'),
('Produção Musical'),
('Microeletrônica'),
('Engenharia de Sistemas Embarcados'),
('Bioinformática'),
('Genômica'),
('Estatística'),
('Matemática Aplicada'),
('Física de Partículas'),
('Astronomia'),
('Geoprocessamento'),
('Sistemas de Informação Geográfica (GIS)'),
('Sustentabilidade'),
('Energias Renováveis'),
('Gestão Ambiental'),
('Tradução'),
('Localização de Software'),
('Coaching de Carreira'),
('Psicologia Organizacional'),
('Coolhunting'),
('Análise de Tendências'),
('Antropologia Digital'),
('Sociologia do Consumo'),
('Investigação Forense Digital'),
('Robótica'),
('Edição de Texto e Revisão');

