export const themes = {
  'auxiliar-cozinha': {
    primary: 'bg-orange-500',
    text: 'text-orange-600',
    border: 'border-orange-200',
    bgLight: 'bg-orange-50',
    icon: 'ChefHat',
    pattern: 'bg-[radial-gradient(#f97316_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#f97316',
    hexSecondary: '#fbbf24',
    hexDark: '#c2410c',
    emoji: '🍳',
  },
  'atendente': {
    primary: 'bg-blue-500',
    text: 'text-blue-600',
    border: 'border-blue-200',
    bgLight: 'bg-blue-50',
    icon: 'MessageSquare',
    pattern: 'bg-[radial-gradient(#3b82f6_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#3b82f6',
    hexSecondary: '#60a5fa',
    hexDark: '#1d4ed8',
    emoji: '😊',
  },
  'estoquista': {
    primary: 'bg-emerald-500',
    text: 'text-emerald-600',
    border: 'border-emerald-200',
    bgLight: 'bg-emerald-50',
    icon: 'Package',
    pattern: 'bg-[radial-gradient(#10b981_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#10b981',
    hexSecondary: '#34d399',
    hexDark: '#047857',
    emoji: '📦',
  },
  'vendas': {
    primary: 'bg-purple-500',
    text: 'text-purple-600',
    border: 'border-purple-200',
    bgLight: 'bg-purple-50',
    icon: 'ShoppingCart',
    pattern: 'bg-[radial-gradient(#8b5cf6_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#8b5cf6',
    hexSecondary: '#a78bfa',
    hexDark: '#6d28d9',
    emoji: '💼',
  },
  'limpeza': {
    primary: 'bg-cyan-500',
    text: 'text-cyan-600',
    border: 'border-cyan-200',
    bgLight: 'bg-cyan-50',
    icon: 'Wind',
    pattern: 'bg-[radial-gradient(#06b6d4_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#06b6d4',
    hexSecondary: '#67e8f9',
    hexDark: '#0e7490',
    emoji: '✨',
  },
  default: {
    primary: 'bg-slate-800',
    text: 'text-slate-800',
    border: 'border-slate-200',
    bgLight: 'bg-slate-50',
    icon: 'Briefcase',
    pattern: 'bg-[radial-gradient(#cbd5e1_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#334155',
    hexSecondary: '#64748b',
    hexDark: '#1e293b',
    emoji: '💼',
  }
};

export type ThemeKey = keyof typeof themes;

export const getTheme = (slug: string) => {
  return themes[slug as ThemeKey] || themes.default;
};
