export const themes = {
  'auxiliar-cozinha': {
    primary: 'bg-orange-500',
    text: 'text-orange-600',
    border: 'border-orange-200',
    bgLight: 'bg-orange-50',
    icon: 'ChefHat',
    pattern: 'bg-[radial-gradient(#f97316_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#f97316',
    hexSecondary: '#fbbf24',
    hexDark: '#c2410c',
    emoji: '🍳',
  },
  gastronomia: {
    primary: 'bg-orange-500',
    text: 'text-orange-600',
    border: 'border-orange-200',
    bgLight: 'bg-orange-50',
    icon: 'ChefHat',
    pattern: 'bg-[radial-gradient(#f97316_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#f97316',
    hexSecondary: '#fbbf24',
    hexDark: '#c2410c',
    emoji: '🍳',
  },
  atendente: {
    primary: 'bg-blue-500',
    text: 'text-blue-600',
    border: 'border-blue-200',
    bgLight: 'bg-blue-50',
    icon: 'MessageSquare',
    pattern: 'bg-[radial-gradient(#3b82f6_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#3b82f6',
    hexSecondary: '#60a5fa',
    hexDark: '#1d4ed8',
    emoji: '😊',
  },
  estoquista: {
    primary: 'bg-emerald-500',
    text: 'text-emerald-600',
    border: 'border-emerald-200',
    bgLight: 'bg-emerald-50',
    icon: 'Package',
    pattern: 'bg-[radial-gradient(#10b981_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#10b981',
    hexSecondary: '#34d399',
    hexDark: '#047857',
    emoji: '📦',
  },
  vendas: {
    primary: 'bg-purple-500',
    text: 'text-purple-600',
    border: 'border-purple-200',
    bgLight: 'bg-purple-50',
    icon: 'ShoppingBag',
    pattern: 'bg-[radial-gradient(#8b5cf6_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#8b5cf6',
    hexSecondary: '#a78bfa',
    hexDark: '#6d28d9',
    emoji: '💼',
  },
  'vendas-atendimento': {
    primary: 'bg-purple-500',
    text: 'text-purple-600',
    border: 'border-purple-200',
    bgLight: 'bg-purple-50',
    icon: 'ShoppingBag',
    pattern: 'bg-[radial-gradient(#8b5cf6_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#8b5cf6',
    hexSecondary: '#a78bfa',
    hexDark: '#6d28d9',
    emoji: '🛒',
  },
  limpeza: {
    primary: 'bg-cyan-500',
    text: 'text-cyan-600',
    border: 'border-cyan-200',
    bgLight: 'bg-cyan-50',
    icon: 'Wind',
    pattern: 'bg-[radial-gradient(#06b6d4_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#06b6d4',
    hexSecondary: '#67e8f9',
    hexDark: '#0e7490',
    emoji: '✨',
  },
  'limpeza-conservacao': {
    primary: 'bg-cyan-500',
    text: 'text-cyan-600',
    border: 'border-cyan-200',
    bgLight: 'bg-cyan-50',
    icon: 'Wind',
    pattern: 'bg-[radial-gradient(#06b6d4_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#06b6d4',
    hexSecondary: '#67e8f9',
    hexDark: '#0e7490',
    emoji: '🧹',
  },
  tecnologia: {
    primary: 'bg-blue-700',
    text: 'text-blue-700',
    border: 'border-blue-200',
    bgLight: 'bg-blue-50',
    icon: 'Code2',
    pattern: 'bg-[radial-gradient(#1d4ed8_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#1d4ed8',
    hexSecondary: '#38bdf8',
    hexDark: '#0c1445',
    emoji: '💻',
  },
  saude: {
    primary: 'bg-green-500',
    text: 'text-green-600',
    border: 'border-green-200',
    bgLight: 'bg-green-50',
    icon: 'Heart',
    pattern: 'bg-[radial-gradient(#22c55e_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#22c55e',
    hexSecondary: '#86efac',
    hexDark: '#14532d',
    emoji: '❤️',
  },
  beleza: {
    primary: 'bg-pink-500',
    text: 'text-pink-600',
    border: 'border-pink-200',
    bgLight: 'bg-pink-50',
    icon: 'Sparkles',
    pattern: 'bg-[radial-gradient(#ec4899_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#ec4899',
    hexSecondary: '#f9a8d4',
    hexDark: '#9d174d',
    emoji: '💅',
  },
  'beleza-estetica': {
    primary: 'bg-pink-500',
    text: 'text-pink-600',
    border: 'border-pink-200',
    bgLight: 'bg-pink-50',
    icon: 'Sparkles',
    pattern: 'bg-[radial-gradient(#ec4899_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#ec4899',
    hexSecondary: '#f9a8d4',
    hexDark: '#9d174d',
    emoji: '💅',
  },
  logistica: {
    primary: 'bg-sky-600',
    text: 'text-sky-700',
    border: 'border-sky-200',
    bgLight: 'bg-sky-50',
    icon: 'Package',
    pattern: 'bg-[radial-gradient(#0284c7_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#0284c7',
    hexSecondary: '#f97316',
    hexDark: '#0c4a6e',
    emoji: '📦',
  },
  'logistica-estoque': {
    primary: 'bg-sky-600',
    text: 'text-sky-700',
    border: 'border-sky-200',
    bgLight: 'bg-sky-50',
    icon: 'Package',
    pattern: 'bg-[radial-gradient(#0284c7_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#0284c7',
    hexSecondary: '#f97316',
    hexDark: '#0c4a6e',
    emoji: '🚚',
  },
  seguranca: {
    primary: 'bg-slate-700',
    text: 'text-slate-700',
    border: 'border-slate-200',
    bgLight: 'bg-slate-50',
    icon: 'Shield',
    pattern: 'bg-[radial-gradient(#475569_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#475569',
    hexSecondary: '#94a3b8',
    hexDark: '#1e293b',
    emoji: '🛡️',
  },
  'seguranca-recepcao': {
    primary: 'bg-slate-700',
    text: 'text-slate-700',
    border: 'border-slate-200',
    bgLight: 'bg-slate-50',
    icon: 'Shield',
    pattern: 'bg-[radial-gradient(#475569_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#475569',
    hexSecondary: '#94a3b8',
    hexDark: '#1e293b',
    emoji: '🛡️',
  },
  educacao: {
    primary: 'bg-indigo-500',
    text: 'text-indigo-600',
    border: 'border-indigo-200',
    bgLight: 'bg-indigo-50',
    icon: 'GraduationCap',
    pattern: 'bg-[radial-gradient(#6366f1_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#6366f1',
    hexSecondary: '#818cf8',
    hexDark: '#3730a3',
    emoji: '📚',
  },
  design: {
    primary: 'bg-violet-500',
    text: 'text-violet-600',
    border: 'border-violet-200',
    bgLight: 'bg-violet-50',
    icon: 'Palette',
    pattern: 'bg-[radial-gradient(#7c3aed_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#7c3aed',
    hexSecondary: '#c4b5fd',
    hexDark: '#4c1d95',
    emoji: '🎨',
  },
  'design-marketing': {
    primary: 'bg-violet-500',
    text: 'text-violet-600',
    border: 'border-violet-200',
    bgLight: 'bg-violet-50',
    icon: 'Palette',
    pattern: 'bg-[radial-gradient(#7c3aed_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#7c3aed',
    hexSecondary: '#c4b5fd',
    hexDark: '#4c1d95',
    emoji: '🎨',
  },
  construcao: {
    primary: 'bg-amber-600',
    text: 'text-amber-700',
    border: 'border-amber-200',
    bgLight: 'bg-amber-50',
    icon: 'HardHat',
    pattern: 'bg-[radial-gradient(#d97706_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#d97706',
    hexSecondary: '#fcd34d',
    hexDark: '#92400e',
    emoji: '🏗️',
  },
  'construcao-civil': {
    primary: 'bg-amber-600',
    text: 'text-amber-700',
    border: 'border-amber-200',
    bgLight: 'bg-amber-50',
    icon: 'HardHat',
    pattern: 'bg-[radial-gradient(#d97706_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#d97706',
    hexSecondary: '#fcd34d',
    hexDark: '#92400e',
    emoji: '🔨',
  },
  administrativo: {
    primary: 'bg-teal-500',
    text: 'text-teal-600',
    border: 'border-teal-200',
    bgLight: 'bg-teal-50',
    icon: 'ClipboardList',
    pattern: 'bg-[radial-gradient(#14b8a6_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#14b8a6',
    hexSecondary: '#5eead4',
    hexDark: '#0f766e',
    emoji: '📋',
  },
  default: {
    primary: 'bg-slate-800',
    text: 'text-slate-800',
    border: 'border-slate-200',
    bgLight: 'bg-slate-50',
    icon: 'Briefcase',
    pattern: 'bg-[radial-gradient(#cbd5e1_1px,transparent_1px)] [background-size:16px_16px] opacity-10',
    hex: '#334155',
    hexSecondary: '#64748b',
    hexDark: '#1e293b',
    emoji: '💼',
  }
};

export type ThemeKey = keyof typeof themes;

export const getTheme = (slug: string) => {
  return themes[slug as ThemeKey] || themes.default;
};
